server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: upiver88

oauth2:
  facebook:
    client_id: 524498068262984
    redirect_uri: http://localhost:8080/facebook/controller/response
    authorize_query: https://graph.facebook.com/oauth/authorize?client_id=524498068262984&redirect_uri=http://localhost:8080/facebook/controller/response
    client_secret: cfacf96b367ad56006aa2241445154f5
    access_token_uri: https://graph.facebook.com/oauth/access_token
    userinfo_uri: https://graph.facebook.com/me
  github:
    client_id: dd4c90b293a7052338f9
    redirect_uri:
    authorize_query: https://github.com/login/oauth/authorize?client_id=dd4c90b293a7052338f9
    client_secret: 04061c224e98c67a9efa631fa5d4db14e70eb286
    access_token_uri: https://github.com/login/oauth/access_token
    userinfo_uri: https://api.github.com/user
  google:
    client_id: 22669341198-16homna5bm8qgno6a4agsf4dnoccaio3.apps.googleusercontent.com
    redirect_uri: http://localhost:8080/google/controller/response
    authorize_query: https://accounts.google.com/o/oauth2/auth?client_id=22669341198-16homna5bm8qgno6a4agsf4dnoccaio3.apps.googleusercontent.com&redirect_uri=http://localhost:8080/google/controller/response&response_type=code&scope=profile
    client_secret: HiK5MRTIVupovjv1ZWXFdNqu
    access_token_uri: https://www.googleapis.com/oauth2/v4/token
    userinfo_uri: https://www.googleapis.com/auth/v2/userinfo.profile?access_token=%s
